# Generated by Django 5.1 on 2024-08-17 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0007_remove_employee_basic_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('program', models.CharField(max_length=50)),
                ('trainer', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(choices=[('room1', 'room1'), ('room2', 'room2'), ('room3', 'room3'), ('room3', 'room3')], max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Trainings', to='Employee.employee')),
            ],
        ),
    ]
