# Generated by Django 5.1 on 2024-08-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='status',
            field=models.CharField(choices=[('inprogress', 'inprogress'), ('completed', 'completed')], default=456, max_length=50),
            preserve_default=False,
        ),
    ]
