# Generated by Django 5.1 on 2024-08-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training_App', '0002_training_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.CharField(default=456, max_length=100),
            preserve_default=False,
        ),
    ]
