# Generated by Django 5.1 on 2024-08-17 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_remove_employee_basic_salary'),
        ('Training_App', '0003_training_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['end_date']},
        ),
        migrations.AlterField(
            model_name='training',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='Employee.employee'),
        ),
        migrations.AlterField(
            model_name='training',
            name='location',
            field=models.CharField(choices=[('room1', 'Room 1'), ('room2', 'Room 2'), ('room3', 'Room 3')], max_length=50),
        ),
        migrations.AlterField(
            model_name='training',
            name='status',
            field=models.CharField(choices=[('inprogress', 'In Progress'), ('completed', 'Completed')], default='inprogress', max_length=50),
        ),
    ]
