# Generated by Django 5.1 on 2024-08-17 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_remove_employee_basic_salary'),
        ('Training_App', '0005_alter_training_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='Employee.employee'),
        ),
    ]
