# Generated by Django 5.1 on 2024-08-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training_App', '0006_alter_training_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='cirtificate',
            field=models.FileField(blank=True, null=True, upload_to='cirtificates/'),
        ),
    ]
