# Generated by Django 5.1 on 2024-08-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll_Integration_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='absences',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
