# Generated by Django 5.1 on 2024-08-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll_Integration_App', '0002_payroll_absences_alter_payroll_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='absences',
        ),
        migrations.AddField(
            model_name='payroll',
            name='absences_in_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='daily_wage',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='working_days_in_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
