# Generated by Django 5.1 on 2024-08-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll_Integration_App', '0003_remove_payroll_absences_payroll_absences_in_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='absences_in_month',
            field=models.PositiveIntegerField(default=28),
        ),
    ]
