# Generated by Django 5.1 on 2024-08-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll_Integration_App', '0005_remove_payroll_daily_wage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='working_days',
        ),
        migrations.AddField(
            model_name='payroll',
            name='daily_wage',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='present_days',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='payroll',
            name='working_days_in_month',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
