# Generated by Django 5.1 on 2024-08-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll_Integration_App', '0006_remove_payroll_working_days_payroll_daily_wage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='daily_wage',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='present_days',
        ),
        migrations.AddField(
            model_name='payroll',
            name='attendance_days_in_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='calculated_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='working_days_in_month',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
