# Generated by Django 5.1 on 2024-08-25 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_alter_employee_profile_picture'),
        ('Performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='Employee.employee'),
        ),
    ]
