# Generated by Django 5.0.6 on 2024-08-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0002_remove_departments_department_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='department_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departments',
            name='department_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
