# Generated by Django 5.1 on 2024-08-26 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0004_department_subdepartment'),
        ('Employee', '0012_alter_employee_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.AddField(
            model_name='subdepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_departments', to='Departments.department'),
        ),
    ]
