# Generated by Django 5.0.6 on 2024-08-12 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in_time', models.TimeField()),
                ('clock_out_time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('On Time', 'On Time'), ('Late', 'Late')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.employee')),
            ],
            options={
                'ordering': ['date', 'employee'],
            },
        ),
    ]
