# Generated by Django 5.1 on 2024-08-13 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0005_alter_employee_annual_leave_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('Positive', 'Positive'), ('Constructive', 'Constructive'), ('Neutral', 'Neutral')], max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Reviewed', 'Reviewed'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedback', to='Employee.employee')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedback', to='Employee.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_feedback', to='Employee.employee')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
