# Generated by Django 5.1 on 2024-08-29 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_type',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='status',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='subject',
        ),
    ]
