# Generated by Django 5.1 on 2024-08-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback_App', '0002_remove_feedback_feedback_type_remove_feedback_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='giver',
            field=models.CharField(max_length=100),
        ),
    ]
