# Generated by Django 5.1 on 2024-08-13 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0003_alter_employee_options_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('Annual', 'Annual'), ('Sick', 'Sick'), ('Maternity', 'Maternity'), ('Paternity', 'Paternity'), ('Unpaid', 'Unpaid'), ('Other', 'Other')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='Employee.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
