# Generated by Django 5.1 on 2024-08-29 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0013_alter_employee_role'),
        ('Leave_Management_App', '0003_leave_applied_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={},
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='end_date',
            new_name='leave_from',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='start_date',
            new_name='leave_to',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='applied_date',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='total_days',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='leave',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='Employee.employee'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Annual', 'Annual'), ('Sick', 'Sick'), ('Maternity', 'Maternity'), ('Paternity', 'Paternity'), ('Unpaid', 'Unpaid')], max_length=20),
        ),
    ]
