# Generated by Django 5.0.6 on 2024-08-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('employee_type', models.CharField(max_length=50)),
                ('joining_date', models.DateField()),
                ('position', models.CharField(max_length=50)),
                ('cv', models.FileField(upload_to='documents/')),
                ('educational_document', models.FileField(upload_to='documents/')),
                ('experience_letter', models.FileField(upload_to='documents/')),
                ('profile_picture', models.ImageField(upload_to='profile_pictures/')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
