# Generated by Django 5.1 on 2024-08-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_alter_employee_options_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='annual_leave_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='maternity_leave_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='paternity_leave_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='sick_leave_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='unpaid_leave_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
