# Generated by Django 5.1 on 2024-08-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_employee_annual_leave_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='annual_leave_balance',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='maternity_leave_balance',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='paternity_leave_balance',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sick_leave_balance',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='unpaid_leave_balance',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
