# Generated by Django 5.1 on 2024-08-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_employee_basic_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='basic_salary',
        ),
    ]
