# Generated by Django 5.1 on 2024-08-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_employee_average_break_time_employee_average_in_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emergency_person_name',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_phone_number',
            field=models.CharField(default=123, max_length=12),
            preserve_default=False,
        ),
    ]
