# Generated by Django 5.1 on 2024-08-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0009_employee_emergency_person_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
    ]
