# Generated by Django 5.1 on 2024-08-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0010_remove_employee_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.FileField(null=True, upload_to='profile_pictures/'),
        ),
    ]
