# Generated by Django 5.1 on 2024-08-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0012_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('director', 'director'), ('employee', 'employee')], max_length=50),
        ),
    ]
